
--1. What is the total revenue generated by male vs. female custmers?
select gender,sum(purchase_amount)as total_revenue from customer_shopping_data group by gender


--2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount from customer_shopping_data where discount_applied = 'yes' and purchase_amount >=(select avg(purchase_amount) from customer_shopping_data)


--3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased,round(avg(review_rating),2) from customer_shopping_data group by item_purchased


--4. Compare the average purchase amounts between Standard and Express Shipping.
select shipping_type,avg(purchase_amount) from   customer_shopping_data where shipping_type in ( 'standard' ,'express') group by shipping_type


--5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select  subscription_status,
count(customer_id)as total_customer,
avg(purchase_amount)as avg_spend,
sum(purchase_amount)as total_spend 
from customer_shopping_data
group by subscription_status


--6. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased,
round(100*sum(case when discount_applied ='yes' then 1 else 0 end) /count(*),2)as discount_rate
from customer_shopping_data 
group by item_purchased
order by discount_rate desc


--7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_tpye as(
select customer_id,
previous_purchases,
case 
    when previous_purchases = 1 then 'new'
    when previous_purchases between 2 and 10 then 'returning'
    else 'loyal' end as customer_segment
from  customer_shopping_data)
select customer_segment ,
count(*)as 'number of segment'
from customer_tpye
group by customer_segment


--8. What are the top 3 most purchased products within each category?
with item_counts as (
select  item_purchased,
category ,count(customer_id)as total_orders, 
row_number() over(partition by category order by count(customer_id) desc ) as item_rank
from customer_shopping_data
group by  item_purchased,category
)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <= 3

--9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(*)repeated_buyers from 
customer_shopping_data
where previous_purchases >5
group  by subscription_status
--10. What is the revenue contribution of each age group?
select age_group ,
sum(purchase_amount) as total_revenue
from customer_shopping_data
group by age_group

